title: "OrthoQA-1k - A larger structured synthetic dataset of orthopedic surgery Q&A"
version: "1.0"
published: "2025-06-16"
tagline: "A large, structured synthetic dataset for Orthopedic surgery question answering."
description: |
  Ortho-1K is a synthetic, structured Q&A dataset generated
  using a templated prompt framework over GPT-3.5-turbo, designed 
  to support medical NLP research in orthopedic surgery. 
  All content is fully synthetic and free of PHI. 
  This dataset enables rapid finetuning and benchmarking of 
  domain-specific language models for clinical decision support, 
  patient education, and surgical consultation use cases.
doi: ""

# metadata for HuggingFace/README  
language:
  - "en"
tags:
  - "machine-learning"
  - "dataset"
  - "orthopedics"
  - "question-answering"
  - "synthetic-data"
  - "medical-nlp"
  - "healthcare"
size_categories:
  - "1K<n<10K"

logo_path: "config/assets/logo.png"
banner_path: "config/assets/banner.png"

# links
github_link: ""
huggingface_link: ""
zenodo_link: ""

# author info
maintainer: "abdullah.ridwan@stratumresearch.org"
contributors:
  - name: "Abdullah Ridwan"
    orcid: "0009-0004-9531-9520"
    email: "abdullah.ridwan@stratumresearch.org"
    affiliation: "Stratum Research"
    role: "creator"
  - name: "Radhyyah Hossain"
    orcid: ""
    email: "radhyyah.hossain@stratumresearch.org"
    affiliation: "Stratum Research"
    role: "creator"
